from typing import Optional, Protocol, Sequence
from .entity import Maquina

class MaquinaRepository(Protocol):
   def get_by_id(self, maquina_id: int) -> Maquina | None: ...
   def create(self, maquina: Maquina) -> Maquina: ...
   def update(self, maquina: Maquina) -> Maquina: ...
   def delete(self, maquina_id: int) -> bool: ...
    