version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      - DATABASE_HOST=${DATABASE_HOST:-163.172.82.28}
      - DATABASE_USER=${DATABASE_USER:-deve}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME:-APP_HARCHA_MAQUINARIA}
      - DATABASE_PORT=${DATABASE_PORT:-3306}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: python run.py