version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: harcha_api_prod
    env_file:
      - .env.production
    environment:
      GUNICORN_WORKERS: 3
      GUNICORN_THREADS: 4
      GUNICORN_LOGLEVEL: info
    expose:
      - "5000"

  nginx:
    image: nginx:1.27-alpine
    container_name: harcha_nginx_prod
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
